<a href="https://colab.research.google.com/github/fish34/sberbank_data_analysis/blob/master/hw_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Упражнение 1

На одном графике изобразите время затраченное на вычисление с использованием массивов numpy и стандартных списков в питоне.  
Для более точных результатов замеряйте время выполнения функции несколько раз и усредняйте. 
* Используйте функцию `z = 2*x**2 + 4*y`
* Перемножение матриц размера n на n

In [1]:
import numpy as np
import time

In [2]:
size_of_vec = 30000
py=np.zeros(100)
num=np.zeros(100)
def python():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = [2*X[i]**2 + 4*Y[i] for i in range(len(X))]
    return time.time() - start

def numpy():
    start = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = 2*X**2 + 4*Y
    return time.time() - start
for i in range(100):
  py[i]=python()
  num[i]=numpy()
print(f'numpy is faster {py.mean()/num.mean()} times')

numpy is faster 55.36232721359182 times


In [3]:
size_of_vec = 30000
py=np.zeros(100)
num=np.zeros(100)
def python():
    start = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = list(map(lambda x,y: x*y, X,Y))
    return time.time() - start

def numpy():
    start = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X*Y
    return time.time() - start

for i in range(100):
  py[i]=python()
  num[i]=numpy()
print(f'numpy is faster {py.mean()/num.mean()} times')

numpy is faster 6.3375094886717225 times


### Упражнение 2
* Создайте массив чисел от 2 до 75. Выведите только нечётные. 
* Присвойте нечётным числам этого массива значение -1.



In [4]:
mas=np.arange(2,76)
filter_arr=mas%2==1
mas[filter_arr]

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69,
       71, 73, 75])

In [5]:
mas[filter_arr]=-1
mas

array([ 2, -1,  4, -1,  6, -1,  8, -1, 10, -1, 12, -1, 14, -1, 16, -1, 18,
       -1, 20, -1, 22, -1, 24, -1, 26, -1, 28, -1, 30, -1, 32, -1, 34, -1,
       36, -1, 38, -1, 40, -1, 42, -1, 44, -1, 46, -1, 48, -1, 50, -1, 52,
       -1, 54, -1, 56, -1, 58, -1, 60, -1, 62, -1, 64, -1, 66, -1, 68, -1,
       70, -1, 72, -1, 74, -1])

### Упражнение 3

* Найдите в документации функцию, которая удаляет из одного массива элементы, которые есть в другом. 
* Приведите примеры использования.

In [6]:
# https://numpy.org/doc/stable/reference/generated/numpy.setdiff1d.html#numpy.setdiff1d

mas1=np.random.randint(0,10,10)
mas2=np.random.randint(0,10,10)
print(mas1,mas2)
diff=np.setdiff1d(mas1,mas2)
print(diff)


[8 5 5 4 9 1 8 3 8 7] [2 7 6 6 7 5 8 4 3 0]
[1 9]


### Упражнение 4

* Создайте случайную квадратную матрицу случайного размера от 10 до 100. 
* Найдите максимум и сумму элементов.
* Поделите каждый элемент матрицы на максимум.
* Отнимите от каждой строки матрицы среднее по строке.
* Замените максимальное значение на -1.

In [7]:
seed=np.random.randint(4,10)
A=np.random.randint(10,100,size=seed**2).reshape(seed,seed)
print(A)
print(f'Max {A.max()}')
print(f'Sum {A.sum()}')
B=A/A.max()
print(B)

[[26 42 27 28 42 98 45 80]
 [91 75 28 46 70 44 91 99]
 [31 88 77 12 41 37 83 85]
 [49 66 94 76 17 30 96 97]
 [44 38 78 66 23 90 62 75]
 [27 27 88 22 32 96 44 52]
 [95 20 83 18 96 21 11 37]
 [81 76 29 27 45 44 33 28]]
Max 99
Sum 3519
[[0.26262626 0.42424242 0.27272727 0.28282828 0.42424242 0.98989899
  0.45454545 0.80808081]
 [0.91919192 0.75757576 0.28282828 0.46464646 0.70707071 0.44444444
  0.91919192 1.        ]
 [0.31313131 0.88888889 0.77777778 0.12121212 0.41414141 0.37373737
  0.83838384 0.85858586]
 [0.49494949 0.66666667 0.94949495 0.76767677 0.17171717 0.3030303
  0.96969697 0.97979798]
 [0.44444444 0.38383838 0.78787879 0.66666667 0.23232323 0.90909091
  0.62626263 0.75757576]
 [0.27272727 0.27272727 0.88888889 0.22222222 0.32323232 0.96969697
  0.44444444 0.52525253]
 [0.95959596 0.2020202  0.83838384 0.18181818 0.96969697 0.21212121
  0.11111111 0.37373737]
 [0.81818182 0.76767677 0.29292929 0.27272727 0.45454545 0.44444444
  0.33333333 0.28282828]]


In [8]:
mean=A.mean(axis=0)
print(mean)
meant=np.tile(mean,(seed,1)).T
print(meant)
A-meant

[55.5   54.    63.    36.875 45.75  57.5   58.125 69.125]
[[55.5   55.5   55.5   55.5   55.5   55.5   55.5   55.5  ]
 [54.    54.    54.    54.    54.    54.    54.    54.   ]
 [63.    63.    63.    63.    63.    63.    63.    63.   ]
 [36.875 36.875 36.875 36.875 36.875 36.875 36.875 36.875]
 [45.75  45.75  45.75  45.75  45.75  45.75  45.75  45.75 ]
 [57.5   57.5   57.5   57.5   57.5   57.5   57.5   57.5  ]
 [58.125 58.125 58.125 58.125 58.125 58.125 58.125 58.125]
 [69.125 69.125 69.125 69.125 69.125 69.125 69.125 69.125]]


array([[-29.5  , -13.5  , -28.5  , -27.5  , -13.5  ,  42.5  , -10.5  ,
         24.5  ],
       [ 37.   ,  21.   , -26.   ,  -8.   ,  16.   , -10.   ,  37.   ,
         45.   ],
       [-32.   ,  25.   ,  14.   , -51.   , -22.   , -26.   ,  20.   ,
         22.   ],
       [ 12.125,  29.125,  57.125,  39.125, -19.875,  -6.875,  59.125,
         60.125],
       [ -1.75 ,  -7.75 ,  32.25 ,  20.25 , -22.75 ,  44.25 ,  16.25 ,
         29.25 ],
       [-30.5  , -30.5  ,  30.5  , -35.5  , -25.5  ,  38.5  , -13.5  ,
         -5.5  ],
       [ 36.875, -38.125,  24.875, -40.125,  37.875, -37.125, -47.125,
        -21.125],
       [ 11.875,   6.875, -40.125, -42.125, -24.125, -25.125, -36.125,
        -41.125]])

In [9]:
A[A==A.max()]=-1
A

array([[26, 42, 27, 28, 42, 98, 45, 80],
       [91, 75, 28, 46, 70, 44, 91, -1],
       [31, 88, 77, 12, 41, 37, 83, 85],
       [49, 66, 94, 76, 17, 30, 96, 97],
       [44, 38, 78, 66, 23, 90, 62, 75],
       [27, 27, 88, 22, 32, 96, 44, 52],
       [95, 20, 83, 18, 96, 21, 11, 37],
       [81, 76, 29, 27, 45, 44, 33, 28]])

### Упражнение 5
* Напишите функцию, которая берет многомерный вещественный массив с пропущенными значениями (np.nan) и возвращает его копию с заполненными пропусками (заменять средним значением всех элементов массива). Если в массиве одни пропущенные значения, заполните их нулями.

In [10]:
A=np.empty(shape=(3,3))
A[:]=np.nan
B=np.array([[1,np.nan,3],[4,5,6],[np.nan,8,9]])

def mfill(arr):
  mean=np.nanmean(arr)
  print(mean)
  if np.isnan(mean):
    arr[:]=0 
  else:
    arr[np.isnan(arr)]=mean   
  return arr
for el in [A,B]:
  print(f'source: {el}, processed: {mfill(el)}')

nan
source: [[nan nan nan]
 [nan nan nan]
 [nan nan nan]], processed: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
5.142857142857143
source: [[ 1. nan  3.]
 [ 4.  5.  6.]
 [nan  8.  9.]], processed: [[1.         5.14285714 3.        ]
 [4.         5.         6.        ]
 [5.14285714 8.         9.        ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: RuntimeWarning: Mean of empty slice
  


In [11]:
np.isnan([np.nan,np.nan])

array([ True,  True])

### Упражнение 6
* Напишите функцию которая нормализирует заданный numpy-массив, так чтобы его значения лежали в интервале $[0, 1]$.

In [12]:
A=np.array([1,46,26,543,54,78,324,90]).reshape(4,-1)
def norm(arr):
  return arr/arr.max()
  #or arr/np.linalg.norm(A)
print(A, norm(A))

[[  1  46]
 [ 26 543]
 [ 54  78]
 [324  90]] [[0.00184162 0.08471455]
 [0.04788214 1.        ]
 [0.09944751 0.14364641]
 [0.59668508 0.16574586]]


### Упражнение 7
* Запишите numpy-array в файл.
* Считайте numpy-array из файла.

In [13]:
A=np.array([1,46,26,543,54,78,324,90]).reshape(4,-1)
fname='test.txt'
np.savetxt(fname,A,fmt='%d')
B=np.loadtxt(fname)
print(A,B)

[[  1  46]
 [ 26 543]
 [ 54  78]
 [324  90]] [[  1.  46.]
 [ 26. 543.]
 [ 54.  78.]
 [324.  90.]]


### Упражнение 8
* Создайте случайный массив
* Найдите в массиве элемент ближайший к данному

In [14]:
A = np.random.randint(0, 1000, 30)
def closest(arr,el):
  diff=arr-el
  return diff.min()+el
print(A,closest(A,10))

[127 767 473 925 517 602 562  46 364 522 956 944  74 361 517 630 896   4
 117 209 782 799 522 636 699 803 260 723 965 616] 4


### Упражнение 9

* Напишите функцию, которая возвращает  $n \times m$ целочисленную матрицу с заданным значением на границах матрицы и с заданным значением внутри

In [15]:
def out(n,m,border,inner,):
  A=np.zeros((n,m),dtype='int64')
  A[:]=inner
  A[[0,n-1],:]=border
  A[:,[0,m-1]]=border
  return A

out(32,55,77,1)

array([[77, 77, 77, ..., 77, 77, 77],
       [77,  1,  1, ...,  1,  1, 77],
       [77,  1,  1, ...,  1,  1, 77],
       ...,
       [77,  1,  1, ...,  1,  1, 77],
       [77,  1,  1, ...,  1,  1, 77],
       [77, 77, 77, ..., 77, 77, 77]])

### Упражнение 10
* Напишите функцию, которая сортирует строки данной матрицы по значениям заданного столбца в порядке убывания. 

In [16]:
A=np.random.randint(0,30,12).reshape(3,4)
A


array([[ 5, 10,  3,  5],
       [28, 24, 10, 17],
       [21, 21,  1,  6]])

In [17]:
def sortbycolumn(arr,col):
  ind=arr[:,col].argsort()
  order=np.flip(ind)
  return arr[order]

sortbycolumn(A,3)

array([[28, 24, 10, 17],
       [21, 21,  1,  6],
       [ 5, 10,  3,  5]])

### Упражнение 11

* Напишите функцию, которая создает двоичную матрицу шахматной доски с заданным shape

Пример 4x4:
```python
[[0, 1, 0, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 1],
 [1, 0, 1, 0]]
```

In [35]:
shape=(7,8)
A=np.zeros(shape,dtype='int64')
def chess(arr,share):
  arr[0:shape[0]:2,0:shape[1]:2]=1
  arr[1:shape[0]:2,1:shape[1]:2]=1
  return arr
chess(A,shape)

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Упражнение 12
* Напишите игру [life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life), используя массивы numpy.
* Визуализируйте интерактивно ее результаты.

